# Generated by Django 4.0.4 on 2022-05-05 05:54

import django.contrib.postgres.fields
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GenericSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'default_vpn_provider',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        default=core.models.get_default_vpn_provider,
                        size=None,
                    ),
                ),
                (
                    'default_from_email',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=core.models.get_from_email,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
