# Generated by Django 4.0.4 on 2022-04-29 00:09

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpn_providers', models.CharField(choices=[('Access', 'Access'), ('CyberGhost', 'CyberGhost'), ('ExpressVPN', 'ExpressVPN')], max_length=20)),
                ('default_vpn_provider', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=core.models.get_default_vpn_provider, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
