# Generated by Django 4.0.4 on 2022-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenericSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vpn_providers",
                    models.CharField(
                        choices=[
                            ("AC", "Access"),
                            ("CY", "CyberGhost"),
                            ("EX", "ExpressVPN"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
