# Generated by Django 4.0.4 on 2022-04-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericsettings',
            name='vpn_providers',
            field=models.CharField(choices=[('Access', 'Access'), ('CyberGhost', 'CyberGhost'), ('ExpressVPN', 'ExpressVPN')], default='Access', max_length=20),
        ),
    ]
